---
#- name: Specify MySQL root password before installing
#  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_db_password | quote}}' vtype='password'
#  become: true
#
#- name: Confirm MySQL root password before installing
#  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_db_password | quote}}' vtype='password'
#  become: true
#

- name: Install MySQL
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - python-mysqldb
    - mysql-server
    - mysql-client
    - libmysqlclient-dev


- name: Ensure MySQL service is up
  service: name=mysql state=started

- name: copy .my.cnf file with root password credentials
  template:
    src=templates/my.cnf
    dest=/root/.my.cnf
    owner=root
    mode=0600


## When first running ansible, mysql root default password is empty.
## So following line login_password={{ mysql_root_db_password }} should 
## be changed to login_password=""
- name: Update MySQL root password for all root accounts
  mysql_user: check_implicit_admin=yes
              login_user=root
              login_password={{ mysql_root_db_password }}
              name=root
              host={{ item }}
              password={{ mysql_root_db_password }}
              priv='*.*:ALL,GRANT'
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  become: true

- name: Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - $inventory_hostname
    - $ansible_hostname
    - localhost

- name: Create MySQL Database
  mysql_db: name={{ deploy_app_name }}
            state=present
            encoding=utf8mb4

- name: Create MySQL User
  mysql_user: name={{ deploy_app_name }}
              priv={{ deploy_app_name }}.*:ALL
              state=present
              password="{{ mysql_app_db_password }}"
