---
- name: get apt repo key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: install apt repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present
    filename: elastic-6.x.list
    update_cache: yes

- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
  tags:
    - elasticsearch

# - name: Install JRE
#   apt: name=default-jre state=latest
#   tags:
#     - elasticsearch

- name: Install JDK
  apt: name=default-jdk state=latest
  tags:
    - elasticsearch


# - name: Download Elasticsearch .deb
#   get_url:
#     url: "https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/{{ elasticsearch_version }}/elasticsearch-{{ elasticsearch_version }}.deb"
#     dest: /root/elasticsearch-{{ elasticsearch_version }}.deb
#   tags:
#     - elasticsearch

# - name: Install Elasticsearch
#   command: dpkg -i /root/elasticsearch-{{ elasticsearch_version }}.deb
#   tags:
#     - elasticsearch

- name: install elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
  tags:
    - elasticsearch

- name: reload systemd config
  systemd: daemon_reload=yes

- name: enable service elasticsearch and ensure it is not masked
  systemd:
    name: elasticsearch
    enabled: yes
    masked: no
  tags:
    - elasticsearch

- name: Ensure Elasticsearch service is up
  action: service name=elasticsearch state=started enabled=yes
  tags:
    - elasticsearch
